<?xml version="1.0"?>
<!DOCTYPE feature_vector_file [
   <!ELEMENT feature_vector_file (comments, data_set+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT data_set (data_set_id, section*, feature*)>
   <!ELEMENT data_set_id (#PCDATA)>
   <!ELEMENT section (feature+)>
   <!ATTLIST section start CDATA ""
                     stop CDATA "">
   <!ELEMENT feature (name, v+)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT v (#PCDATA)>
]>

<feature_vector_file>

   <comments></comments>

	<data_set>
		<data_set_id>C:\Users\Giuseppe\Desktop\Music CA\MIDIs\Azalea Town.mid</data_set_id>
		<feature>
			<name>Number of Pitches</name>
			<v>4,1E1</v>
		</feature>
		<feature>
			<name>Number of Pitch Classes</name>
			<v>1,1E1</v>
		</feature>
		<feature>
			<name>Range</name>
			<v>5,1E1</v>
		</feature>
		<feature>
			<name>Strong Tonal Centres</name>
			<v>2E0</v>
		</feature>
		<feature>
			<name>Mean Pitch</name>
			<v>6,6E1</v>
		</feature>
		<feature>
			<name>Mean Pitch Class</name>
			<v>4,41E0</v>
		</feature>
		<feature>
			<name>Most Common Pitch</name>
			<v>7,3E1</v>
		</feature>
		<feature>
			<name>Most Common Pitch Class</name>
			<v>1E0</v>
		</feature>
		<feature>
			<name>Interval Between Most Prevalent Pitches</name>
			<v>8E0</v>
		</feature>
		<feature>
			<name>Pitch Variability</name>
			<v>1,207E1</v>
		</feature>
		<feature>
			<name>Most Common Melodic Interval</name>
			<v>0E0</v>
		</feature>
	</data_set>

</feature_vector_file>